### PR TITLE
Add flip expect animations and example activity

### PR DESCRIPTION
**Pull request by TheWhiteLlama**
I've added Flip Animations and CameraDistance Animations to the system. I also thought about adding a possibility to cull the faces depending on the current rotation, but then I'd have to consider some solutions for this first.

If you like the idea of the implementaion of this flip animation I'd appreciate it if you'd review it @florent37 :)

### CODE REVIEW

**Comment by florent37** [comment]
yes I like it, just one think the flip is always a 360° flip ? if no, it should change the view width

**Comment by florent37** [comment]
this should extend RotationExpectation I think

**Comment by TheWhiteLlama** [comment]
Okay I will have a further look into that! So as I understood you'd also let FlipExpectation extend RotationExpectation, are there special reasons for that? :)

Currently I've set the flip to a 180 degree flip. I think this might be useful when having two-sided views. But I think I probably should implement some kind of backface culling? What do you think?

**Comment by florent37** [comment]
It should extend RotationExpectation because I use this expectation to know the final rotation of the view. And depending of this rotation, I will know the futur dimensions of the view.
So if the flip is fully, the dimension stay the same,
if not, it will change

**Comment by TheWhiteLlama** [comment]
Hmm okay makes sense. So I guess it depends on you, since I could not think of a scenario where the user actually wants to rotate the view on its x- and y-axis by a non 180 degree angle. That's why I did not take a change of dimensions into account.

**Pull request merged**
