### PR TITLE
Add an ExpectAnim sequencer and other improvements

### PR DESCRIPTION
**Pull request by HozakaN**
I needed some improvement over ExpectAnim. It can be useful to other people so I've decided to share those ones.

Changes include a sequencer to play multiple ExpectAnim objects one after another. It's not the perfect design and I'm sure we can improve it on many aspects that we can discuss.
It includes a tag system built into ExpectAnim, so we can have some information in the listeners.
I also added start and end listeners onto ExpectAnim reset method.

To make it work as a submodule of my own project, I updated the tools versions. Hope you don't mind.

### CODE REVIEW

**Comment by florent37** [comment]
hi, i'm for the idea of playing sequentially ExpectAnims, can you provide a sample of your implementation please ?

**Comment by HozakaN** [comment]
Hi. Actually I've worked a bit on this and came up with a much more elegant strategy.
I've included sample and update to README.MD for the two features I've added.
I've also changed the reset method so that it can play it back.

**Comment by florent37** [comment]
what about a `thenExpect`or `then().expect()`?

```java
anim1 = new ExpectAnim()
        .expect(view1)
        .toBe(
                bottomOfParent()
        )
        .thenExpect(view2)
        .toBe(
                outOfScreen(Gravity.END)
        )
        .toAnimation()
        .setDuration(1000);
```

**Comment by HozakaN** [comment]
Yeah it makes sense

**Comment by HozakaN** [comment]
Any news?

**Comment by florent37** [comment]
Sorry I didn't had time to test, btw I can publish a new version with it if you want, can you check if all my other samples always work and then upgrade the version number from the global gradle file ?

my CI will publish it automatically ;)

**Comment by HozakaN** [comment]
No worries. I've seen you've been busy with RxAnimations :)
I'll check that.
About CI, circleci is failing but I don't know why, each time I check the gradle dependencies tab is loading infinitely

**Comment by florent37** [comment]
circleci fails about the buildtools version, like all CI it's not up to date

**Comment by florent37** [comment]
the first 2 samples does not work anymore, I'll try to fix it this morning

**Comment by HozakaN** [comment]
I'm sorry I'm budy for a few days.
I was thinking of some possible issues with my solution. I'll check that in a week if you are ok with that.

**Pull request closed without merging**
